### PR TITLE
[Enhancement] new company landing page #184

### LINKED ISSUE #184: [Enhancement] New Company Landing/Information Page
This is the screen when I log in for the first time as a new company.  Look nice but at some point we will probably want to work on a new Company Landing page with steps to set up your new company or at-least have a written handout for them to follow to successfully set up new company into Granite. 

image

### PR DESCRIPTION
**Pull request by James1x0**
closes #184 

first-steps-intro_desktop
first-steps-intro_iphone

### CODE REVIEW

**Comment by James1x0** [comment]
Thoughts @JavaLavaMT ?

**Comment by JavaLavaMT** [comment]
I love it, what if you make the congratulating box she just a tad bit longer.

**Comment by James1x0** [comment]
@JavaLavaMT Ah like timeout time? I'd agree

**Comment by JavaLavaMT** [comment]
yeah, not too long maybe like 3-4 sec

**Comment by James1x0** [comment]
@JavaLavaMT timeout time is in the route, how about you adjust it and commit whenever you get a chance?

**Comment by JavaLavaMT** [comment]
I like that idea, I will work on this today.

**Comment by JavaLavaMT** [comment]
done 

image

**Pull request merged**
