### PR TITLE
[Enhancement] Reflow the org chart to the right

### LINKED ISSUE #422: [Enhancement] Reflow the org chart to the right
reflow the org chart to the right and not down.

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #422

### CODE REVIEW

**Comment by James1x0** [comment]
@JavaLavaMT Screenshot?

**Comment by JavaLavaMT** [comment]
screen shot 2018-12-21 at 12 03 48 pm
screen shot 2018-12-21 at 12 04 19 pm

**Comment by James1x0** [comment]
@JavaLavaMT Could I get a screenshot of when you choose a "stand in"? There should be a blinking red segment.

**Comment by JavaLavaMT** [comment]
When Offboarding Reorganization

image

**Pull request merged**
